name: first workflow
on: workflow_dispatch
jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello team"
      - name: showing time
        run: echo "Time is" $date
