name: second workflow
on: push
jobs:
  Checking_Actions:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 5
      - name: install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
